<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="polycreate" nsURI="http://www.example.org/polycreate" nsPrefix="polycreate">
  <eClassifiers xsi:type="ecore:EClass" name="Mission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" lowerBound="1"
        upperBound="-1" eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eOperations name="run"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eOperations name="run"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        upperBound="-1" eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eOperations name="isValid"/>
    <eOperations name="run"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeSequence" lowerBound="1"
        eType="#//AlternativeSequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeSequence" eSuperTypes="#//Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextSequence" lowerBound="1"
        eType="#//Sequence"/>
  </eClassifiers>
</ecore:EPackage>
