<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="polycreate" nsURI="http://www.example.org/polycreate" nsPrefix="polycreate">
  <eClassifiers xsi:type="ecore:EClass" name="Mission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" lowerBound="1"
        upperBound="-1" eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalAction" abstract="true" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        upperBound="-1" eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeSequence" lowerBound="1"
        eType="#//AlternativeSequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeSequence" eSuperTypes="#//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rotate" eSuperTypes="#//PhysicalAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degrees" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="90"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveForward" eSuperTypes="#//PhysicalAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grab" eSuperTypes="#//PhysicalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Release" eSuperTypes="#//PhysicalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wall" abstract="true" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectInFront" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="WallLeft" eSuperTypes="#//Wall"/>
  <eClassifiers xsi:type="ecore:EClass" name="WallRight" eSuperTypes="#//Wall"/>
  <eClassifiers xsi:type="ecore:EClass" name="WallFront" eSuperTypes="#//Wall"/>
</ecore:EPackage>
